### ISSUE TITLE
set memory

### ISSUE THREAD

**Issue by wokier** [oxygenhq/oxygen#267]
We would like to raise the memory used by the test execution
As oxygen is based on Node, is it possible to pass the max_old_space_size value using the oxygen.conf.js file ?

**Comment by romovs** [comment]
Changing nodejs parameters via oxygen.conf.js is not possible.
But it can be changed via environment variables. For example to set `max_old_space_size` for the current CMD session:
```
set NODE_OPTIONS=--max_old_space_size=4096
oxygen ...
```

Or just add `NODE_OPTIONS=--max_old_space_size=4096` to system or user environment variables to make it persistent.

**Comment by wokier** [comment]
Note: this article help a lot


https://getridbug.com/node-js/how-do-i-determine-the-correct-max-old-space-size-for-node-js/
