### ISSUE TITLE
Desktop suite: Oxygen CLI command not running suite

### ISSUE THREAD

**Issue by naeemakram** [oxygenhq/oxygen#44]
I saved the sample JSON to a file in Oxygen docs "Getting Started CLI" section.
Saved it to the disk and ran it with two sample.js test files. 
The tests run fine individually, but when I run them through the suite, the following error is shown:
SCRIPT_ERROR
Unexpected token, expected ; (2:14)

**Comment by erandame** [comment]
Hi naeemakram
Documentation has been updated
see the following links
https://docs.oxygenhq.org/howtos/how-tos/project-configuration
some of the CLI features have been deprecated and will be updated soon
but in the mean time keep a look on the CLI page and it should be updated soon
https://docs.oxygenhq.org/oxygen-cli/introduction-and-usage

**Comment by erandame** [comment]
By the way, the Oxygen support page is where the action takes place
http://discuss.oxygenhq.org/c/support

**Comment by naeemakram** [comment]
Hi there, thanks very much for sharing. I'll check it out. I made a bunch of videos about Oxygen, have you seen any? Check this: 
https://youtu.be/wYclpxyvth8

**Comment by erandame** [comment]
Hi Naeem, Thanks so much for the films, i shared them in our channel
I would love to show you a few more features if you want
will contact you via mail

**Comment by naeemakram** [comment]
Great! 
Feel free to get in touch through my gmail naeem.akram.malik.
